name: pinocchio_add_light
services:
  main:
    image: ghcr.io/arduino/app-bricks/python-apps-base:0.12.0
    volumes:
    - type: bind
      source: /home/arduino/ArduinoApps/pinocchio_add_light
      target: /app
    - type: bind
      source: /dev
      target: /dev
    - type: bind
      source: /run/udev
      target: /run/udev
      read_only: true
    - type: bind
      source: /run/user/1000/pipewire-0
      target: /run/user/1000/pipewire-0
    - type: bind
      source: /run/arduino-router.sock
      target: /run/arduino-router.sock
    - type: bind
      source: /sys/class/leds/blue:user
      target: /sys/class/leds/blue:user
    - type: bind
      source: /sys/class/leds/green:user
      target: /sys/class/leds/green:user
    - type: bind
      source: /sys/class/leds/red:user
      target: /sys/class/leds/red:user
    - type: bind
      source: /sys/class/leds/blue:bt
      target: /sys/class/leds/blue:bt
    - type: bind
      source: /sys/class/leds/green:wlan
      target: /sys/class/leds/green:wlan
    - type: bind
      source: /sys/class/leds/red:panic
      target: /sys/class/leds/red:panic
    device_cgroup_rules:
    - c 226:* rmw
    - c 506:* rmw
    - c 81:* rmw
    - c 116:* rmw
    ports:
    - 7000:7000
    user: 1000:1000
    group_add:
    - 44
    - 29
    - 991
    - 20
    - 1001
    entrypoint: /run.sh
    extra_hosts:
    - msgpack-rpc-router:host-gateway
    labels:
      cc.arduino.app: "true"
      cc.arduino.app.main: "true"
      cc.arduino.app.path: /home/arduino/ArduinoApps/pinocchio_add_light
    environment:
      APP_HOME: /home/arduino/ArduinoApps/pinocchio_add_light
      BOARD_NAME: unoq
      HOST_IP: 192.168.1.117
      MODELS_PATH: /var/lib/arduino-app-cli/models
      XDG_RUNTIME_DIR: /run/user/1000
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 5m
